export interface OrderData {
  service_id: Number,
  subservice_id: Number,
  amount: Number,
  bgMusicId: Number,
  format: String,
  report: Boolean,
  latitude: Number,
  longitude: Number,
  date: Date,
  name: String,
  surname: String,
  streetName: String,
  streetNumber: Number,
  apartmentNumber: Number,
  city: String,
  zip: Number,
  nip: Number,
  email: String,
  tel: Number,
  alias: String,
  description: String,
  price: Number,
}
